import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type Language = 'bg' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  bg: {
    'nav.menu': 'Меню',
    'nav.locations': 'Локации',
    'nav.catering': 'Кетъринг',
    'nav.gallery': 'Галерия',
    'nav.about': 'За нас',
    'nav.contact': 'Контакт',
    'nav.lunch': 'Обедно меню',
    'nav.careers': 'Кариери',
    'nav.reserve': 'Резервирай',
    'nav.call': 'Обади се',
    'hero.title': 'Автентичен вкус на',
    'hero.subtitle': 'италианската традиция',
    'hero.tagline': 'Насладете се на най-добрата пица на пещ, барбекю и средиземноморска кухня в сърцето на София.',
    'hero.viewMenu': 'Виж Менюто',
    'hero.viewLunch': 'Обедно Меню',
    'hero.findLocation': 'Намери Локация',
    'quick.call': 'Обади се',
    'quick.reserve': 'Резервирай',
    'quick.delivery': 'Доставка',
    'quick.menu': 'Меню',
    'section.exploreMenu': 'Разгледайте нашето меню',
    'section.chefsFavorites': 'Любимите на шефа',
    'section.chefsFavoritesDesc': 'Открийте нашите най-обичани ястия, приготвени с най-пресните съставки и страст.',
    'section.viewFullMenu': 'Виж цялото меню',
    'section.visitUs': 'Посетете ни',
    'section.visitUsDesc': 'Три локации в София, всяка със своя уникален чар.',
    'section.cateringTitle': 'Кетъринг за вашите специални събития',
    'section.cateringDesc': 'От корпоративни обяди до сватбени тържества, ние пренасяме вкуса на Ветрило до вашето място. Професионално обслужване и индивидуални менюта за всеки повод.',
    'section.requestOffer': 'Запитване за оферта',
    'footer.brandInfo': 'Автентични италиански вкусове и традиционно българско гостоприемство от 2003 г. Присъединете се към нас за незабравимо преживяване.',
    'footer.ourLocations': 'Нашите локации',
    'footer.rights': 'Всички права запазени.',
    'footer.privacy': 'Политика за поверителност',
    'footer.terms': 'Условия за ползване',
    'menu.title': 'Нашето Меню',
    'menu.subtitle': 'Подбрана селекция от автентични италиански пици, пресни салати и традиционно барбекю.',
    'menu.noItems': 'Все още няма намерени артикули в тази категория. Проверете отново скоро!',
    'menu.ingredients': 'Съставки',
    'menu.allergens': 'Съдържа глутен и млечни продукти. Моля, информирайте нашия персонал за всякакви алергии.',
    'menu.moreInfo': 'Повече инфо',
    'menu.lessInfo': 'По-малко инфо',
    'locations.title': 'Нашите Локации',
    'locations.subtitle': 'Намерете най-близкото Пица Ветрило и се насладете на прекрасна храна в уютна атмосфера.',
    'locations.openNow': 'Отворено сега',
    'locations.directions': 'Упътвания',
    'locations.reserve': 'Резервирай',
    'locations.orders': 'За поръчки',
    'locations.freeDelivery': 'над 20 лв безплатна доставка',
    'locations.mapTitle': 'Интерактивна карта',
    'locations.mapDesc': 'Разгледайте нашите локации в София и намерете най-близката до вас.',
    'locations.openGoogleMaps': 'Отвори в Google Maps',
    'catering.heroTitle': 'Кетъринг за събития в София',
    'catering.heroSubtitle': 'Подобрете вашия специален повод с нашите авторски ястия и професионално обслужване.',
    'catering.eventsTitle': 'Събития, които обслужваме',
    'catering.servicesTitle': 'Нашите кетъринг услуги',
    'catering.servicesDesc': 'Ние предлагаме пълно кетъринг изживяване, като се грижим за всеки детайл, за да можете да се съсредоточите върху вашите гости.',
    'catering.customMenus': 'Индивидуални менюта',
    'catering.customMenusDesc': 'Всяко събитие е уникално. Нашите готвачи ще работят с вас, за да създадат индивидуално меню, което отговаря на вашата тема, бюджет и диетични изисквания.',
    'catering.formTitle': 'Форма за запитване',
    'catering.formName': 'Име',
    'catering.formPhone': 'Телефон',
    'catering.formEmail': 'Имейл',
    'catering.formEventType': 'Тип събитие',
    'catering.formGuestCount': 'Брой гости',
    'catering.formNotes': 'Бележки',
    'catering.formSend': 'Изпрати запитване',
    'catering.formPlaceholderName': 'Вашето пълно име',
    'catering.formPlaceholderNotes': 'Разкажете ни повече за вашето събитие...',
    'gallery.title': 'Галерия',
    'gallery.subtitle': 'Визуално пътешествие през нашата кухня, нашите ресторанти и моментите, които споделяме.',
    'about.title': 'За Нас',
    'about.subtitle': 'Традиция на качество, семейство и перфектното парче от 2003 г.',
    'about.since': 'От 2003 г.',
    'about.legacyTitle': 'ЗА НАС',
    'about.legacyDesc1': 'Пицария "Ветрило" отваря, за първи път, врати през 2003 година в гр. София, кв. Борово. За кратко време превлякохме голям брой клиенти с перфектната си кухня и достъпни цени. Днес, вече има два нови ресторанта, които да отговорят на изискванията на всеки.',
    'about.legacyDesc2': 'Ние Ви предлагаме качество на ниски цени и уютна обстановка, подходяща за всеки. Специално за нашите клиенти предлагаме и опция доставка по домовете, градина с детски кът, както и специални партньорски условия при кетъринг услуги от наша страна за Вас при специални поводи или събития.',
    'about.philosophy': 'ПО-ДОБРИ ОТ ДРУГИТЕ',
    'about.philosophyDesc': 'Ние Ви предлагаме качество на ниски цени и уютна обстановка, подходяща за всеки.',
    'about.family': 'Семейството на първо място',
    'about.familyDesc': 'Ветрило е място за всеки. От детски рождени дни до тихи семейни вечери, ние създаваме атмосфера, в която всеки се чувства у дома си.',
    'about.reputation': 'Местна репутация',
    'about.reputationDesc': 'Гордеем се, че сме част от оживената кулинарна сцена на София и сме ангажирани да даваме обратно на общността, която ни подкрепя в продължение на почти две десетилетия.',
    'about.careersTitle': 'КАРИЕРИ В ПИЦАРИИ "ВЕТРИЛО"',
    'about.careersDesc': 'Ако желаете да се развивате в динамична среда в сферата на ресторантьорския бизнес ние сме готови да ви посрещнем. Ще ви предложим обучение, шанс за развитие, както и възможност за много добри доходи. Не се колебайте, а кандидайствайте при нас:',
    'about.applyNow': 'Кандидатствайте тук',
    'contact.title': 'Контакт',
    'contact.subtitle': 'Имате въпрос, обратна връзка или искате да резервирате специално събитие? Ние сме тук, за да помогнем.',
    'contact.getInTouch': 'Свържете се с нас',
    'contact.mainOffice': 'Главен офис',
    'contact.mainOfficeLoc': 'София, България',
    'contact.followUs': 'Последвайте ни',
    'contact.sendMessage': 'Изпрати съобщение',
    'contact.email': 'Имейл',
    'contact.formSubject': 'Тема',
    'contact.formMessage': 'Съобщение',
    'contact.formPlaceholderSubject': 'Как можем да помогнем?',
    'contact.formPlaceholderMessage': 'Вашето съобщение...',
    'contact.formSend': 'Изпрати съобщение',
    'contact.quickLinks': 'Бързи връзки към нашите ресторанти',
    'cat.All': 'Всички',
    'cat.Pizza': 'Пица',
    'cat.BBQ': 'Барбекю',
    'cat.Pasta': 'Паста',
    'cat.Salads': 'Салати',
    'cat.Desserts': 'Десерти',
    'cat.Lunch Menu': 'Обедно меню',
    'cat.Starters': 'Предястия',
    'cat.Soups': 'Супи',
    'cat.Risotto': 'Ризото',
    'cat.Fish': 'Риба',
    'cat.Main Dishes': 'Основни ястия',
    'cat.Oven Dishes': 'Ястия на пещ',
    'cat.Burgers': 'Бургери',
    'cat.Sides': 'Гарнитури',
    'cat.Food': 'Храна',
    'cat.Interior': 'Интериор',
    'cat.Atmosphere': 'Атмосфера',
    'cat.Events': 'Събития',
    'event.Weddings': 'Сватби',
    'event.Corporate events': 'Корпоративни събития',
    'event.Team building': 'Тиймбилдинг',
    'event.Kids parties': 'Детски партита',
    'event.Garden parties': 'Градински партита',
    'event.Coffee breaks': 'Кафе паузи',
    'event.Cocktail events': 'Коктейлни събития',
    'event.Proms': 'Абитуриентски балове',
    'service.Menu planning': 'Планиране на меню',
    'service.Food preparation': 'Приготвяне на храна',
    'service.Delivery & Setup': 'Доставка и подредба',
    'service.Professional Staff': 'Професионален персонал',
    'service.Equipment Rental': 'Наем на оборудване',
    'service.Clean up service': 'Почистване',
    'form.required': 'Това поле е задължително',
    'form.invalidEmail': 'Невалиден имейл адрес',
    'form.invalidPhone': 'Невалиден телефонен номер',
    'form.minGuests': 'Минимум 1 гост',
    'form.successTitle': 'Благодарим!',
    'form.successCatering': 'Вашето запитване беше изпратено успешно. Ще се свържем с вас скоро.',
    'form.successContact': 'Вашето съобщение беше изпратено успешно. Ще се свържем с вас скоро.',
    'form.sendAnother': 'Изпрати ново',
    'locations.servedAreas': 'Обслужвани райони',
    'locations.viewLunchMenu': 'Обедно меню (PDF)',
    'footer.delivery': 'Доставка',
    'footer.orderOn': 'Поръчай от',
    'locations.deliveryTitle': 'Поръчайте онлайн',
    'locations.deliveryDesc': 'Поръчайте любимите си ястия от Ветрило чрез нашите партньори за доставка.',
    'catering.formSelectEvent': 'Изберете тип събитие',
  },
  en: {
    'nav.menu': 'Menu',
    'nav.locations': 'Locations',
    'nav.catering': 'Catering',
    'nav.gallery': 'Gallery',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.lunch': 'Lunch Menu',
    'nav.careers': 'Careers',
    'nav.reserve': 'Reserve',
    'nav.call': 'Call',
    'hero.title': 'Authentic Taste of',
    'hero.subtitle': 'Italian Tradition',
    'hero.tagline': 'Experience the finest wood-fired pizza, BBQ, and Mediterranean cuisine in the heart of Sofia.',
    'hero.viewMenu': 'View Menu',
    'hero.viewLunch': 'Lunch Menu',
    'hero.findLocation': 'Find Location',
    'quick.call': 'Call Us',
    'quick.reserve': 'Reserve',
    'quick.delivery': 'Delivery',
    'quick.menu': 'Menu',
    'section.exploreMenu': 'Explore Our Menu',
    'section.chefsFavorites': "Chef's Favorites",
    'section.chefsFavoritesDesc': 'Discover our most loved dishes, prepared with the freshest ingredients and passion.',
    'section.viewFullMenu': 'View Full Menu',
    'section.visitUs': 'Visit Us',
    'section.visitUsDesc': 'Three locations across Sofia, each with its own unique charm.',
    'section.cateringTitle': 'Catering for Your Special Events',
    'section.cateringDesc': 'From corporate lunches to wedding celebrations, we bring the taste of Vetrilo to your venue. Professional service and customized menus for any occasion.',
    'section.requestOffer': 'Request Offer',
    'footer.brandInfo': 'Authentic Italian flavors and traditional Bulgarian hospitality since 2003. Join us for a memorable dining experience.',
    'footer.ourLocations': 'Our Locations',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'menu.title': 'Our Menu',
    'menu.subtitle': 'A curated selection of authentic Italian pizzas, fresh salads, and traditional BBQ.',
    'menu.noItems': 'No items found in this category yet. Check back soon!',
    'menu.ingredients': 'Ingredients',
    'menu.allergens': 'Contains gluten and dairy. Please inform our staff about any allergies.',
    'menu.moreInfo': 'More Info',
    'menu.lessInfo': 'Less Info',
    'locations.title': 'Our Locations',
    'locations.subtitle': 'Find the nearest Pizza Vetrilo and enjoy a wonderful meal in a cozy atmosphere.',
    'locations.openNow': 'Open Now',
    'locations.directions': 'Directions',
    'locations.reserve': 'Reserve',
    'locations.orders': 'For orders',
    'locations.freeDelivery': 'free delivery over 20 lv',
    'locations.mapTitle': 'Interactive Map',
    'locations.mapDesc': 'Explore our locations across Sofia and find the one closest to you.',
    'locations.openGoogleMaps': 'Open in Google Maps',
    'catering.heroTitle': 'Catering for Events in Sofia',
    'catering.heroSubtitle': 'Elevate your special occasion with our signature dishes and professional service.',
    'catering.eventsTitle': 'Events We Cater',
    'catering.servicesTitle': 'Our Catering Services',
    'catering.servicesDesc': 'We provide a full-service catering experience, ensuring every detail is handled with care so you can focus on your guests.',
    'catering.customMenus': 'Custom Menus',
    'catering.customMenusDesc': 'Every event is unique. Our chefs will work with you to create a customized menu that fits your theme, budget, and dietary requirements.',
    'catering.formTitle': 'Inquiry Form',
    'catering.formName': 'Name',
    'catering.formPhone': 'Phone',
    'catering.formEmail': 'Email',
    'catering.formEventType': 'Event Type',
    'catering.formGuestCount': 'Guest Count',
    'catering.formNotes': 'Notes',
    'catering.formSend': 'Send Inquiry',
    'catering.formPlaceholderName': 'Your full name',
    'catering.formPlaceholderNotes': 'Tell us more about your event...',
    'gallery.title': 'Gallery',
    'gallery.subtitle': 'A visual journey through our kitchen, our restaurants, and the moments we share.',
    'about.title': 'About Us',
    'about.subtitle': 'A tradition of quality, family, and the perfect slice since 2003.',
    'about.since': 'Since 2003',
    'about.legacyTitle': 'ABOUT US',
    'about.legacyDesc1': 'Pizza Vetrilo opened its doors for the first time in 2003 in Sofia, Borovo district. In a short time, we attracted a large number of customers with our perfect cuisine and affordable prices. Today, there are already two new restaurants to meet everyone\'s requirements.',
    'about.legacyDesc2': 'We offer you quality at low prices and a cozy atmosphere suitable for everyone. Especially for our customers, we also offer a home delivery option, a garden with a children\'s corner, as well as special partnership conditions for catering services for your special occasions or events.',
    'about.philosophy': 'BETTER THAN OTHERS',
    'about.philosophyDesc': 'We offer you quality at low prices and a cozy atmosphere suitable for everyone.',
    'about.family': 'Family First',
    'about.familyDesc': 'Vetrilo is a place for everyone. From kids\' birthday parties to quiet family dinners, we create an atmosphere where everyone feels at home.',
    'about.reputation': 'Local Reputation',
    'about.reputationDesc': 'We are proud to be a part of Sofia\'s vibrant food scene and are committed to giving back to the community that has supported us for nearly two decades.',
    'about.careersTitle': 'CAREERS AT PIZZA VETRILO',
    'about.careersDesc': 'If you want to develop in a dynamic environment in the field of restaurant business, we are ready to welcome you. We will offer you training, a chance for development, as well as the opportunity for very good income. Do not hesitate, apply with us:',
    'about.applyNow': 'Apply here',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have a question, feedback, or want to book a special event? We\'re here to help.',
    'contact.getInTouch': 'Get in Touch',
    'contact.mainOffice': 'Main Office',
    'contact.mainOfficeLoc': 'Sofia, Bulgaria',
    'contact.followUs': 'Follow Us',
    'contact.sendMessage': 'Send a Message',
    'contact.email': 'Email',
    'contact.formSubject': 'Subject',
    'contact.formMessage': 'Message',
    'contact.formPlaceholderSubject': 'How can we help?',
    'contact.formPlaceholderMessage': 'Your message...',
    'contact.formSend': 'Send Message',
    'contact.quickLinks': 'Quick Links to Our Restaurants',
    'cat.All': 'All',
    'cat.Pizza': 'Pizza',
    'cat.BBQ': 'BBQ',
    'cat.Pasta': 'Pasta',
    'cat.Salads': 'Salads',
    'cat.Desserts': 'Desserts',
    'cat.Lunch Menu': 'Lunch Menu',
    'cat.Starters': 'Starters',
    'cat.Soups': 'Soups',
    'cat.Risotto': 'Risotto',
    'cat.Fish': 'Fish',
    'cat.Main Dishes': 'Main Dishes',
    'cat.Oven Dishes': 'Oven Dishes',
    'cat.Burgers': 'Burgers',
    'cat.Sides': 'Sides',
    'cat.Food': 'Food',
    'cat.Interior': 'Interior',
    'cat.Atmosphere': 'Atmosphere',
    'cat.Events': 'Events',
    'event.Weddings': 'Weddings',
    'event.Corporate events': 'Corporate events',
    'event.Team building': 'Team building',
    'event.Kids parties': 'Kids parties',
    'event.Garden parties': 'Garden parties',
    'event.Coffee breaks': 'Coffee breaks',
    'event.Cocktail events': 'Cocktail events',
    'event.Proms': 'Proms',
    'service.Menu planning': 'Menu planning',
    'service.Food preparation': 'Food preparation',
    'service.Delivery & Setup': 'Delivery & Setup',
    'service.Professional Staff': 'Professional Staff',
    'service.Equipment Rental': 'Equipment Rental',
    'service.Clean up service': 'Clean up service',
    'form.required': 'This field is required',
    'form.invalidEmail': 'Invalid email address',
    'form.invalidPhone': 'Invalid phone number',
    'form.minGuests': 'Minimum 1 guest',
    'form.successTitle': 'Thank you!',
    'form.successCatering': 'Your inquiry was sent successfully. We will contact you soon.',
    'form.successContact': 'Your message was sent successfully. We will contact you soon.',
    'form.sendAnother': 'Send another',
    'locations.servedAreas': 'Served Areas',
    'locations.viewLunchMenu': 'Lunch Menu (PDF)',
    'footer.delivery': 'Delivery',
    'footer.orderOn': 'Order on',
    'locations.deliveryTitle': 'Order Online',
    'locations.deliveryDesc': 'Order your favorite dishes from Vetrilo through our delivery partners.',
    'catering.formSelectEvent': 'Select event type',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('vetrilo-language');
    return (saved === 'bg' || saved === 'en') ? saved : 'bg';
  });

  const handleSetLanguage = (lang: Language) => {
    localStorage.setItem('vetrilo-language', lang);
    setLanguage(lang);
  };

  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
